### Start a new character
POST http://localhost:3000/api/v1/character-builder/start
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

> {% client.global.set("characterId", response.body.data.characterId) %}

### Patch character
POST http://localhost:3000/api/v1/character-builder/patch-character
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "characterId": "{{characterId}}",
    "data": {
        "name": "Test Character",
        "attributes": {
            "strength": 7
        }
    }
}
