name: Chenowyn

on:
  push:
    branches: [ "develop", "feature/aa-54-chenowyn-unit-tests" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: TurboRepo cache setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Build app and dependencies
        run: npx turbo run build --filter=chenowyn...

      - name: Chenowyn unit tests
        run: npm -w apps/chenowyn run test
        env:
          PUBLIC_API_HOST: ${{ vars.PUBLIC_API_HOST }}
          PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ vars.CLERK_PUBLISHABLE_KEY }}
